### ISSUE TITLE
Weird emojis after upgrade

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuro.polymtl.ca#89]
A recent modification (I suspect it is d0d5064ff22172774993549b176e12a2c845ec32, @mguaypaq can confirm) changed the appearance of the page, including the emojis, which now appear within a box:

![image](https://user-images.githubusercontent.com/2482071/231623721-2d19b9ff-17e1-43b1-9064-76481d201e3b.png)

Note that the intranet has a mix of those:

![image](https://user-images.githubusercontent.com/2482071/231623772-137a6930-a4e3-4029-a665-ea9a5f2430d6.png)

The ones with the box are written as:
~~~
`❤️`
~~~
Whereas the ones without the box are written as:
~~~
<span>❤️</span>
~~~ 

Few questions:
- am I the only one seeing these boxes (i'm on macos with chrome)?
- does anyone see the boxes with the formatting from "<span>"?
- does writing emojis without "`" or without "\<span>" also produce the box? If not, I suggest we go for this, unless there is a good reason to keep those.

**Comment by mguaypaq** [comment]
I see the same thing (all boxes for the external website, some boxes for the intranet, firefox on debian). I'll try out the variations you suggest and make sure there are no boxes anywhere.

**Comment by mguaypaq** [comment]
Ah, now I see the reason for including "\<span>": it's to trigger the following CSS rule:
https://github.com/neuropoly/intranet.neuro.polymtl.ca/blob/2fc91df449025396d813c90aef9a01aab6fce2bf/_static/theme.css#L39-L46
This makes the leading emojis in the table of contents on the left side have all the same size, so that the page titles are all aligned. So the real solution is to standardize on "\<span>". I'll do that now.

**Comment by mguaypaq** [comment]
Fixed in https://github.com/neuropoly/neuro.polymtl.ca/commit/0075a3ee1f00e16c8e77a66535fd6c7f14b0c0c7.
